// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "douyin/cmd/api/biz/router/comment"
	favorite "douyin/cmd/api/biz/router/favorite"
	feed "douyin/cmd/api/biz/router/feed"
	message "douyin/cmd/api/biz/router/message"
	publish "douyin/cmd/api/biz/router/publish"
	relation "douyin/cmd/api/biz/router/relation"
	user "douyin/cmd/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	relation.Register(r)

	publish.Register(r)

	message.Register(r)

	feed.Register(r)

	favorite.Register(r)

	comment.Register(r)

}
