// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/initialize"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	registry, info := initialize.InitRegistry();
	h := server.Default(
		server.WithRegistry(registry, info))
	register(h)
	h.Spin()
}
