// Code generated by hertz generator.

package relation

import (
	"douyin/cmd/api/pkg/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationactionMw() []app.HandlerFunc {
	// 管理关注，必须登录
	return []app.HandlerFunc{
		middleware.NoOrWrongTokenAbort,
	}
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followlistMw() []app.HandlerFunc {
	// 查看关注列表，必须登录
	return []app.HandlerFunc{
		middleware.TokenUserIdSame,
	}
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerlistMw() []app.HandlerFunc {
	// 查看粉丝列表，必须登录，并且参数是有token也有userid
	return []app.HandlerFunc{
		middleware.TokenUserIdSame,
	}
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// 查看好友列表，必须登录，并且参数是有token也有userid
	return []app.HandlerFunc{
		middleware.TokenUserIdSame,
	}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}
