// Code generated by hertz generator.

package user

import (
	"douyin/cmd/api/pkg/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// 查看用户自己的信息，必须登录，并且也是Token+UserId
	return []app.HandlerFunc{
		middleware.TokenUserIdSame,
	}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// 登录不需要token
	return nil
}

func _registerMw() []app.HandlerFunc {
	// 注册不需要token
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
