// Code generated by hertz generator.

package comment

import (
	"douyin/cmd/api/pkg/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentactionMw() []app.HandlerFunc {
	// 操作评论，必须登录
	return []app.HandlerFunc{
		middleware.NoOrWrongTokenAbort,
	}
}

func _commentlistMw() []app.HandlerFunc {
	// 获取评论列表，是否登录了，随便
	return []app.HandlerFunc{
		middleware.ParseTokenAndContinue,
	}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}
