// Code generated by hertz generator.

package feed

import (
	"douyin/cmd/api/pkg/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// 任何人都可以看视频，是否登录了，随便
	return []app.HandlerFunc{
		middleware.ParseTokenAndContinue,
	}
}

func _feed0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
